version: '3.9'

services:
    hkey-demo-cas-server:
        build: .
        image: hdce/hkeydemocasserver:1.0.0
        container_name: hkeydemocasserver
        restart: unless-stopped
        ports:
          - 9000:9000
        volumes:
          - /etc/localtime:/etc/localtime:ro
        logging:
          driver: "json-file"
          options:
            max-size: "20m"
