version: '3.4'

services:
    cas-server:
        build: .
        image: cas-server:1.0.0
        container_name: cas-server
        restart: unless-stopped
        ports:
          - 8000:8000
        volumes:
          - /etc/localtime:/etc/localtime:ro
        logging:
          driver: "json-file"
          options:
            max-size: "20m"
