name: Build and Publish Docker image

on:
  workflow_dispatch:
  push:
    branches: [master]

env:
  REPOSITORY_NAME: hdce/hkey-demo-cas-server

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REPOSITORY_NAME }}:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
