# Generated by Django 3.2.23 on 2023-11-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hkey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="huser",
            name="netId",
            field=models.CharField(
                blank=True, default=None, help_text="netID", max_length=16, null=True, unique=True, verbose_name="netId"
            ),
        ),
        migrations.AlterField(
            model_name="huser",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
    ]
