# Generated by Django 2.2.28 on 2023-11-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hkey", "0002_auto_20231129_2249"),
    ]

    operations = [
        migrations.AlterField(
            model_name="huser",
            name="first_name",
            field=models.CharField(blank=True, max_length=30, verbose_name="first name"),
        ),
    ]
